meta:
  root: C:\Users\vanln\Downloads\Hydro-AI-Platform\wflow_model\inputs

dtm:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  path: chelsa.tif
  meta:
    category: topography
    paper_doi: 10.1038/sdata.2017.122
    paper_ref: Karger et al. (2017)
    source_license: CC BY 4.0
    source_url: http://chelsa-climate.org/downloads/
    source_version: 1.2

chirps_global:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  meta:
    category: meteo
    paper_doi: 10.3133/ds832
    paper_ref: Funk et al (2014)
    source_license: CC
    source_url: https://www.chc.ucsb.edu/data/chirps
    source_version: v2.0
  path: chirps_global.nc
  unit_add:
    time: 86400

era5:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  meta:
    category: meteo
    history: Extracted from Copernicus Climate Data Store; resampled by Deltares to
      daily frequency
    paper_doi: 10.1002/qj.3803
    paper_ref: Hersbach et al. (2019)
    source_license: https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products
    source_url: https://doi.org/10.24381/cds.bd0915c6
    source_version: ERA5 daily data on pressure levels
  path: era5.nc
  unit_add:
    temp: -273.15
    temp_max: -273.15
    temp_min: -273.15
    time: 86400
  unit_mult:
    kin: 0.000277778
    kout: 0.000277778
    precip: 1000
    press_msl: 0.01

era5_hourly:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  meta:
    category: meteo
    history: Extracted from Copernicus Climate Data Store
    paper_doi: 10.1002/qj.3803
    paper_ref: Hersbach et al. (2019)
    source_license: https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products
    source_url: https://doi.org/10.24381/cds.bd0915c6
    source_version: ERA5 hourly data on pressure levels
  path: era5_hourly.nc
  unit_add:
    temp: -273.15
  unit_mult:
    kin: 0.000277778
    kout: 0.000277778
    precip: 1000
    press_msl: 0.01

gadm_level1:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  meta:
    category: geography
    notes: last downloaded 2020-10-19; license required for commercial use
    source_author: gadm
    source_license: https://gadm.org/license.html
    source_url: https://gadm.org/download_world.html
    source_version: 1.0
  path: gadm_level1.gpkg

   
soil_data_vector:
  data_type: GeoDataFrame
  driver: vector
  uri: soil.geojson
  metadata:
    category: soil

landuse_data_vector:
  data_type: GeoDataFrame
  driver: vector
  uri: land.geojson
  metadata:
    category: landuse