root: model
mode: w

grid:
  elevation: maps/dtm.tif

  theta_s: maps/theta_s.tif
  theta_r: maps/theta_r.tif
  ksat: maps/k_sat_ver.tif
  soil_thickness: maps/soil_depth.tif
  m: maps/conductivity_decay.tif
  c: maps/brooks_corey.tif

  landuse: maps/land.tif
  lai: maps/LAI.tif
  root_depth: maps/root_depth.tif
  interception: maps/interception.tif
  manning_n: maps/manning_n.tif
  albedo: maps/albedo.tif
  kc: maps/kc.tif

basin:
  method: river_burn
  river_threshold: 200